@echo off
setlocal EnableDelayedExpansion

REM =========================================================
REM Nome da pasta da aula dentro de cada aluno
REM =========================================================
set "AULA_NOME=06-aula06_Administracao_Gerenciamento-02"

REM =========================================================
REM IDENTIFICADORES INTERNOS DAS TURMAS
REM =========================================================
set TURMAS=T1 T2 T3 T4

REM =========================================================
REM NOMES REAIS DAS TURMAS
REM =========================================================
set NOME_TURMA_T1=ADS-DS3P40
set NOME_TURMA_T2=ADS-DS3Q40
set NOME_TURMA_T3=ADS-DS3R40
set NOME_TURMA_T4=ADS-DS2P40

REM =========================================================
REM LISTA DE ALUNOS POR TURMA
REM =========================================================
set ALUNOS_T1=ANDERSON_RAULINO_DA_SILVA-F3620J8 ANDERSON_XAVIER_DE_LIMA-H74HEB9 BARBARA_COSTA_NASCIMENTO-H603064 BRUNA_MEDEIROS_DE_AGUIAR-R815544 CAMILY_DE_SOUSA_OLIVEIRA_ROCHA-R8620H4 CARLOS_EDUARDO_SILVA_SANTANA-F362EF1 CAUA_HENRIQUE_R_DOS_SANTOS-R434FI4 CAUAN_NUNES_LOPES-H6771G9 CLEYTON_ALVES_DA_COSTA-G77AIA8 DANILO_SALGADO_PERALTA_RIBEIRO-R868GI1 DAVID_GABRIEL_SILVA_DE_JESUS-F361DG6 DOUGLAS_VINICIUS_M_DOS_SANTOS-H6094I1 EDER_RODRIGUES_DE_ALMEIDA-R8459C7 FREDSON_SILVA_DOS_SANTOS-R427FB0 GABRIEL_GONCALVES_ZAGO-H75GHA1 GABRIEL_ROQUE_DOS_SANTOS-R6607G5 GUILHERME_SOUSA_DOS_SANTOS-H520495 HECTOR_FABRO_PELLEGRINO-R660IJ4 IGOR_ZABAY_DOS_SANTOS_SILVA-H75BEJ1 ISABELLE_GEORGIA_M_DE_SOUZA-R8378I6 JOAO_PEDRO_SILVA_CARVALHO-N001AE7 JOAO_VITOR_FREITAS_DE_OLIVEIRA-H755HH9 KAREN_DE_SOUSA_FARIA-R8522D0 LEONARDO_ARAUJO_FREIRES-R659EI9 LINCOLN_G_S_A_BARCELLOS-H7501D3 LORRANY_SILVA_AMORIM-G71CJI0 LUCAS_SOUZA_SANTANA-R5837H9 MATHEUS_BRIGANTI_DE_OLIVEIRA-H74FGI8 MAYSA_PONT_LOPES-T160GF8 MIKAEL_MACEDO_DA_SILVA-H671CE9 NICOLAS_TEIXEIRA_DE_AGUIAR-R849244 RAQUEL_BARBOSA_DE_SOUZA-H70GIB0 SAMUEL_GONCALVES_SILVA-G9960J0 THAISLA_LUIZA_SILVA_OLIVEIRA-R194655
set ALUNOS_T2=BRENO_BRITO_ALMEIDA-H768594 BRUNO_ALVES_DE_SOUZA-R8662A7 EDUARDO_DE_SOUSA_PEREIRA-H759CH8 GUILHERME_VELOSO_DOS_SANTOS-R861DH7 HENRIQUE_ALEXANDRE_DAMACENO-H75JAC6 HENRIQUE_OLIVEIRA_GOMES-R8607D0 ISAAC_LIMA_MARTINS-R860922 LUISA_DOS_SANTOS_FIALHO-R8708B6 MARIANE_CARNEIRO_SANTOS-R852IG6 MATHEUS_DA_SILVA_BRITO-R839DA4 MATHEUS_FERREIRA_PINHEIRO-R807053 MICHEL_FARIAS_DA_SILVA-R6607C2 MIGUEL_DOS_SANTOS_M_SIROMA-R540EA6 NICOLAS_ZEMELLA_DE_MATOS-R582639 PEDRO_EDUARDO_PAIVA_MEIRELES-R8699H4 RAMON_BRIAN_G_DOS_SANTOS-R852369 RAPHAEL_CAIQUE_DA_S_NEGREIROS-R850765 RICHARD_RODRIGUES_MEDEIROS-H755565 TAYNARA_NOGUEIRA_DOS_SANTOS-R8439J1 THAMYRES_BANDEIRA_SANTOS-H6882F0 THIAGO_FERREIRA_DIAS-R218BC1 VITOR_ALEXANDRE_DE_J_AMORIM-H66EIH4 VITOR_LUIZ_LUTA_FERNANDES-R465993 VITORIA_DE_OLIVEIRA_VITOR-R503IE5 YEDA_GOMES_DOS_SANTOS_CUSTODIO-R872696
set ALUNOS_T3=ANTONIO_FABIO_RIBEIRO_SAMPAIO-H57HED2 BRUNA_SILVA_DOS_SANTOS-H662893 GABRIEL_PIMENTA_DE_JESUS-H638879 GABRIEL_REZENDE_DE_BARROS-H64CJJ4 GUILHERME_AUGUSTO_G_DE_MELO-H624HJ8 GUSTAVO_RODRIGUES_DE_BARROS-R693627 HENDREW_DOS_SANTOS_BRAZ-H76FBE0 HENRIQUE_BASTOS_LAET-R671IG1 JERFFERSON_DE_SOUZA_NASCIMENTO-H471273 JOAO_VICTOR_RODRIGUES_SILVA-R832384 LUCAS_GABRIEL_MONTEIRO_SILVA-R865118 LUIS_FERNANDO_ANDRADE_SANTOS-H712742 LUIZA_NASCIMENTO_DA_CONCEICAO-H660467 MANUEL_DOUGLAS_SILVA_ALVES-H675AE0 MATHEUS_CAVALCANTE_DE_ALMEIDA-R8506E5 MATHEUS_RENATO_B_ESTEVO-R864CB0 MATHEUS_SANTOS_RIBEIRO-G73IBG5 PEDRO_HENRIQUE_DE_P_MEDEIROS-R8514D9 PEDRO_HENRIQUE_F_DE_SOUZA-R826511 PEDRO_LIMA_DE_ALMEIDA_SOUZA-R802698 RAMON_SANTOS_SILVA-H751616 RHAUAN_SILVA_ARAUJO-R830110
set ALUNOS_T4=BRUNO_SILVA_DE_SOUZA-F3661B5 CAIO_ALVES_DOS_SANTOS-R933EB6 DAVID_PEREIRA_MENDES-H78IIF9 DIEGO_DUARTE_DE_ANDRADE-H78IIB6 ERICKLIS_V_S_EVANGELISTA-H948746 GABRIEL_NONATO_EMERENCIANO-H783216 GABRIEL_ROCHA_SANTOS-T274427 IRAN_ALVES_DOS_SANTOS-H7635D7 JESSICA_BORGES_OLIVEIRA-R9520A6 JOAO_GABRIEL_DE_OLIVEIRA_FILIE-R958825 JOAO_PEDRO_DE_OLIVEIRA-T232341 JOAO_PEDRO_SALEM_MARQUES_SILVA-H7891I8 JORDAN_SILVERIO_DE_SOUSA-T277973 JOSE_OZIEL_SILVA_DO_NASCIMENTO-H77CBF4 KAUE_FERREIRA_DA_SILVA-H779286 LUAN_DE_JESUS_SILVA-R922DC5 LUAN_OLIVEIRA_RUSSO-T307FD5 LUCAS_NEUBAUER_LAPPAS_LINHARES-H789GA6 PAULO_FELIX_DA_SILVA_ARAUJO-H779669 PEDRO_HENRIQUE_M_DA_SILVA-R952DA5 RAYANE_DOS_SANTOS_FALCAO-H790AC7 THAINA_RODRIGUES_PAIVA-F363IC2 THIAGO_SANTOS_DO_CARMO-H75FFF1 VICTHOR_HUGO_S_A_DE_ALMEIDA-F3650I9 VICTOR_FLOHR_FAGUNDES-R941JE0

REM =========================================================
REM PROCESSA CADA TURMA -> ALUNO -> AULA -> EXERCICIOS
REM (execute este .bat a partir da raiz do repositorio)
REM =========================================================
for %%T in (%TURMAS%) do (

    call set "PASTA_TURMA=%%NOME_TURMA_%%T%%"
    call set "LISTA_ALUNOS=%%ALUNOS_%%T%%"

    echo.
    echo Processando turma !PASTA_TURMA!

    mkdir "!PASTA_TURMA!" 2>nul

    for %%A in (!LISTA_ALUNOS!) do (

        echo   Criando estrutura para !PASTA_TURMA!\%%A\%AULA_NOME%

        mkdir "!PASTA_TURMA!\%%A" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%" 2>nul

        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-01" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-02" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-03" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-04" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-05" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-06" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-07" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-08" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-09" 2>nul
        mkdir "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-10" 2>nul

        (echo #exercicio1)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-01\enunciado1.txt"
        (echo //exercicio1) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-01\exercicio1.sql"
        (echo #exercicio2)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-02\enunciado2.txt"
        (echo //exercicio2) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-02\exercicio2.sql"
        (echo #exercicio3)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-03\enunciado3.txt"
        (echo //exercicio3) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-03\exercicio3.sql"
        (echo #exercicio4)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-04\enunciado4.txt"
        (echo //exercicio4) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-04\exercicio4.sql"
        (echo #exercicio5)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-05\enunciado5.txt"
        (echo //exercicio5) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-05\exercicio5.sql"
        (echo #exercicio6)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-06\enunciado6.txt"
        (echo //exercicio6) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-06\exercicio6.sql"
        (echo #exercicio7)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-07\enunciado7.txt"
        (echo //exercicio7) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-07\exercicio7.sql"
        (echo #exercicio8)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-08\enunciado8.txt"
        (echo //exercicio8) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-08\exercicio8.sql"
        (echo #exercicio9)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-09\enunciado9.txt"
        (echo //exercicio9) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-09\exercicio9.sql"
        (echo #exercicio10)  > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-10\enunciado10.txt"
        (echo //exercicio10) > "!PASTA_TURMA!\%%A\%AULA_NOME%\exercicio-10\exercicio10.sql"

    )

)

echo.
echo Estrutura criada com sucesso para %AULA_NOME%.
pause